ARG ImageVersion

FROM rockylinux/rockylinux:$ImageVersion-cci as cci-micro-build
ARG ImageVersion
RUN yum install --installroot /mnt/rootfs coreutils-single glibc-minimal-langpack --releasever $ImageVersion --setopt install_weak_deps=false --nodocs -y && yum --installroot /mnt/rootfs clean all
RUN rm -rf /mnt/rootfs/var/cache/* /mnt/rootfs/var/log/dnf* /mnt/rootfs/var/log/yum.*

FROM scratch
LABEL org.opencontainers.image.title="Rocky Linux common micro image" \
      org.opencontainers.image.description="Very small image which doesn't install the package manager." \
      org.opencontainers.image.source="https://github.com/rocky-linux/sig-cloud-instance-images" \
      org.opencontainers.image.authors="Rocky Linux SIG Cloud Team,Magauer Lukas <lukas@magauer.eu>"

COPY --from=cci-micro-build /mnt/rootfs/ /
COPY --from=cci-micro-build /etc/yum.repos.d/* /etc/yum.repos.d/
CMD /bin/sh
