---
name: CI build for 2nd layer images

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  IMAGE_REGISTRY: docker.io
  IMAGE_ACCOUNT: rockylinux

jobs:
  run_image_builds:
    strategy:
      matrix:
        version:
          - 8
          - 9
        arch:
          - amd64
          - arm64
          - ppc64le
          - s390x
        type:
          - micro
          - init
        exclude:
          - version: 8
            arch: ppc64le
          - version: 8
            arch: s390x
    runs-on: ubuntu-latest
    name: Test the image build
    steps:
      - uses: actions/checkout@v3

      - name: Install qemu dependency
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static

      - name: Build image
        uses: redhat-actions/buildah-build@v2
        id: build-image
        with:
          archs: ${{ matrix.arch }}
          build-args: |
            ImageVersion=${{ matrix.version }}
          containerfiles: |
            ./Containerfile-${{ matrix.type }}
          labels: |
            name=rockylinux
            version=${{ matrix.version }}-ubi-${{ matrix.type }}
          tags: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_ACCOUNT }}/rockylinux:${{ matrix.version }}-ubi-${{ matrix.type }}
